version: '3'
services:
  desktop:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "5900:5900"  # Expose VNC port to the host
    volumes:
      - ~/.Xauthority:/root/.Xauthority:rw  # Ensure VNC can connect to X display
    restart: unless-stopped
    stdin_open: true  # Keep stdin open for interactive apps
    tty: true  # Allocate a pseudo-TTY